### PR TITLE
Paginated submissions by project

### PR DESCRIPTION
**Pull request by Sujanadh**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Describe this PR

Submissions by project are organized in paginated form for the submission table.

## Response

```
{
  "results": [
    {
      "start": "2023-12-28T14:14:15.400+05:45",
      "end": "2023-12-28T14:15:04.773+05:45",
      "today": "2023-12-28",
      .
      .
      .
      "deviceId": "collect:qKQrgKKs1LrYoFoC",
      "edits": 0,
      "formVersion": "2023-12-28T08:25:29Z"
    }
  ],
  "pagination": {
    "has_next": false,
    "has_prev": false,
    "next_num": null,
    "page": 1,
    "pages": 1,
    "prev_num": null,
    "per_page": 13,
    "total": 3
  }
}
```

## Checklist before requesting a review

- 📖 Read the FMTM Contributing Guide: <https://github.com/hotosm/fmtm/blob/main/CONTRIBUTING.md>
- 📖 Read the FMTM Code of Conduct: <https://github.com/hotosm/fmtm/blob/main/CODE_OF_CONDUCT.md>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

### CODE REVIEW

**Comment by spwoodcock** [comment]
Looks good 👍 

I wonder how performant it is pulling the data from the S3 zip.
I envisioned using that only for downloads, but if performance is ok then it makes sense to use the zip (instead of either adding extra database tables for submissions, or querying odkcentral again).

There are 5 linting errors from pre-commit (ruff) by the way - since I fixed all of the linting errors, each PR has to pass before it can be merged 😄

**Comment by Sujanadh** [comment]
The performance is better and quicker than querying odkcentral.
And for the pre commit how should i run it ? is there any command to run it locally?

**Comment by spwoodcock** [comment]
I will fix the errors for now so I can merge a dependent PR.

Added docs about pre-commit here: https://docs.hotosm.org/dev-guide/pre-commit/#pre-commit-python-tool

**Comment by Sujanadh** [comment]
looks good :+1:

**Comment by spwoodcock** [comment]
The linting errors that need to be fixed before merge can be found here: https://results.pre-commit.ci/run/github/548162511/1705657705.XzQPdfFGQL-82ADpm8lEng

**Comment by Sujanadh** [comment]
Fixed those errors raised by pre-commit.

**Pull request merged**
