### PR TITLE
Simplify infographics API usage (reuse Entities data)

### PR DESCRIPTION
**Pull request by NSUWAL123**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation
- [x] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue
- Related to #1521 

## Describe this PR
This PR contains work to calculate the submissions count on the frontend for `Form Submissions`, `Mapped vs Validated` charts, and card counts. 

For now I have commented the frontend API calls for the Submissions chart, once it's QA done then I will remove the code.

## Screenshots
image

### CODE REVIEW

**Comment by NSUWAL123** [comment]
I have commented on previous API calls for the infographics for now. Once QA is done, I will remove all those commented API call codes.

**Comment by NSUWAL123** [comment]
Sure, I will have look on those

**Comment by NSUWAL123** [comment]
@spwoodcock, although I fixed the spelling pre-commit error again it's showing the error though the code has been modified.

**Comment by spwoodcock** [comment]
Looks all good now!

**Pull request merged**
