### PR TITLE
feat: edit project form with form category WIP

### PR DESCRIPTION
**Pull request by varun2948**

### CODE REVIEW

**Comment by varun2948** [comment]
Need backend support after some backend work is done update form will be good to go 
@nrjadkry

**Comment by robsavoye** [comment]
Is this supposed to still be a draft ?

**Comment by varun2948** [comment]
@nrjadkry are we good to go on this update form api?

**Comment by nrjadkry** [comment]
@varun2948 Not yet. I am about to update this and will inform you.

**Comment by nrjadkry** [comment]
@varun2948 I have updated this in backend. Please have a look and let me know if you faced any issue

**Pull request merged**
