### PR TITLE
Add image to user profile

### PR DESCRIPTION
**Pull request by Sujanadh**
# Updates

1. New DbUser field `profile_img` is created to store logged in user 's profile image.
2. Updated auth_routes so as to save it in the database. Here, i have added portion of code to save image in existing users(already logged-in users) too which might be removed later.
3. Created a function `update_task_history` to populate `task_history` with `username`, `status`(extracted from the action_text to keep track of task status history) and `profile_img` .

### CODE REVIEW

**Review by spwoodcock — CHANGES_REQUESTED** [review]
Do we need to store the profile picture in our db when it's stored in OSM anyway? Was it something requested by someone?

When the frontend makes the call to the /me endpoint the profile picture URL is returned & should be stored in the frontend state.

**Comment by spwoodcock** [comment]
Also, a backend test seems to be broken by this change

**Comment by Sujanadh** [comment]
Yes, you are right. Frontend makes the call to the `/me` endpoint to get the profile picture of current logged-in user only. But, to keep the track of history of user who updated the submission before we need to save their profile picture.

**Comment by spwoodcock** [comment]
Got you - thanks for clarifying. 

I assume you are working on a submission dashboard with profile pictures included 👍

The picture is an extra piece of user data we store, if we need to declare a data protection policy in the future.

**Comment by spwoodcock** [comment]
Could you add a revert migration please & I will merge 😄

**Comment by Sujanadh** [comment]
Sure.

**Comment by Sujanadh** [comment]
Previously i had merged feat-submission-page branch to this branch, to use same code to check. I mistakely pushed changes along with the merged contents of branch feat-submission-page. That's why i reset the changes and pushed the migration change. :smiley:

**Review by spwoodcock — APPROVED** [review]

**Comment by spwoodcock** [comment]
Thanks @Sujanadh , the revert looks good, but if you see the folder structure for the migrations it would be good to be consistent with the others. There is a revert folder for migration reversions (we need these for users that accidentally update, but may need to go back a version)

**Comment by Sujanadh** [comment]
Thanks  :+1: @spwoodcock  for the guidance.

**Pull request merged**
