### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Balofire**
#135 #164

### CODE REVIEW

**Comment by robsavoye** [comment]
An open source project shouldn't link to a google doc. For this particular issue, I'd talk to Petya, and have her review the other changes to the contributing doc.

**Comment by Balofire** [comment]
> An open source project shouldn't link to a google doc. For this particular issue, I'd talk to Petya, and have her review the other changes to the contributing doc.

Okay, thank you for the feedback. I've deleted that file and I'm working on making a new file that will have all the content within it without linking. I have also created a new file about structures to improve documentation.

**Comment by robsavoye** [comment]
I think rather than linking to the Miro board, which may not always be accessible, the basics should be extracted into a short document or flowchart.

**Comment by Balofire** [comment]
> I think rather than linking to the Miro board, which may not always be accessible, the basics should be extracted into a short document or flowchart.

I'm on it.

**Comment by Balofire** [comment]
@robsavoye I have added the basic information about the field mapper, field mapping coordinator and validator. I still left the links below in case the viewers wanted to see the full details when the Miro board is accessible

**Pull request merged**
