### PR TITLE
Feat create edit organization

### PR DESCRIPTION
**Pull request by NSUWAL123**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Issue
- #1067
- #1036 

## Describe this PR
This PR includes the following works done: 
1. A new UI flow on creating an organization. First, consent details form will be displayed & if filled only then allowed to proceed to another step to fill organization details form.
2. A new UI design for create/edit organization.
3. Edit organization has also been added.

## Screenshots
- Consent Form
image
image

- Create Organization
image
image

- Edit Organization
image
image

- Approve Organization
image
image

### CODE REVIEW

**Comment by spwoodcock** [comment]
Sorry! Please convert from draft and request review when ready 👍 

I was planning to review and ask a question:
- We ask for the OSM profile in the form.
- Instead it should be possible to put the form behind login, then we automatically know which user requests it.
- So I think we could remove that field and automatically extract it.

**Comment by manjitapandey** [comment]
Yeah, we can remove the osm profile. In future, if request for organisation form shall be the feature which can be accessed without login, we may need the user osm profile.

**Comment by NSUWAL123** [comment]
@spwoodcock, you can merge this PR now. The Create/Edit organization has some fields like `Email` & `Type of applied organization` in the form but the backend needs to be done. 
Note: 
For now edit organization can be accessed by: 
- /edit-organization/:id
The approve organization form can be accessed by: 
- /approve-organization/:id (reject/approve is not completed)

**Comment by spwoodcock** [comment]
Nice!

As part of this PR, should we remove the old organisation creation code?

And also update the project creation page to link here when the user clicks to create a new org?

**Comment by NSUWAL123** [comment]
Once this PR get merged, @manjitapandey will do some QA then I will update the project creation + btn link, and remove the old organization create code

**Pull request merged**
