### PR TITLE
Fix project details map

### PR DESCRIPTION
**Pull request by NSUWAL123**
This PR contains new Project Details UI for Mobile View as said by Ivan.
image
image

### CODE REVIEW

**Comment by ivangayton** [comment]
Wow, this looks great! I guess there are some failing tests, which presumably need to be addressed, but this looks a *lot* more like a serious mobile map UI!

**Comment by varun2948** [comment]
yeah will have a look into it on the test cases.

**Comment by varun2948** [comment]
@nrjadkry @spwoodcock i see pre-commit is getting triggered for backend code. can you look into it and confirm ?

**Comment by spwoodcock** [comment]
@varun2948 yep the pre-commit.ci workflow isn't selective for what it runs on - it runs on the entire codebase.

A big task I have coming up (it would be great if you guys could help too 🙏), is to fix all of the linting errors in the codebase.
The frontend is covered as eslint rules are automatically enforced.
The backend needs a refactor to remove all of the lint errors though.

Run `pre-commit install && pre-commit run --all-files` to see them.

**Comment by spwoodcock** [comment]
So in summary the pre-commit workflow will fail until this refactor is done.
I keep it enabled, as it autoformats our PRs for us (which is handy).

The failing pytest workflow will be solved in #900 and is unrelated to this PR.

**Comment by varun2948** [comment]
Sure we will also replicate it in our codebases and will fix it in our side.

**Comment by nrjadkry** [comment]
Fixing all the pre commit errors might take time. So, it might be okay, we we merge this frontend Pull requests and refactor and fix pre commit errors gradually in the upcoming pull requests. @spwoodcock

**Comment by spwoodcock** [comment]
Completely agree 👍

The issue is that the test cases are broken so we can't merge and deploy currently. 

First on my agenda tomorrow!

**Comment by varun2948** [comment]
@spwoodcock so should we merge this for now?

**Comment by spwoodcock** [comment]
I'll merge it and see what happens 🤷‍♂️

I have a feeling test will fail before deploy.

**Comment by spwoodcock** [comment]
Seems like the deploy was all fine 😁 (sorry for the delay then)

I mistakenly thought I had modified the workflows on `development` but it must just be in the test case branch.

**Comment by varun2948** [comment]
@spwoodcock thats fine Sam, but we should fix this pre-commit issue and let the test case and all the build check on merge or PR fluent enough to not be saying any red cross X, which basically is failing builds. right ?

**Comment by varun2948** [comment]
yeah i will make sure everyone is upto date with the latest development

**Pull request merged**
