### PR TITLE
add ODKConvert.md

### PR DESCRIPTION
**Pull request by Ndacyayisenga-droid**
Hi @rsavoye I just created a quick draft write up, just wanted to know if am on the right track. I going to mark this PR a draft for now

### CODE REVIEW

**Comment by robsavoye** [comment]
This should be under the odkconvert repository instead of the FMTM one. :-)

**Comment by Ndacyayisenga-droid** [comment]
This should be under the odkconvert repository instead of the FMTM one. :-)

**Comment by robsavoye** [comment]
Sorry for the confusion. It's only under FMTM because I was grouping all the documentation tasks in one place for Outreachy. It's a touch complicated that odkconvert is part of FMTM, but also a standalone project.

**Comment by Ndacyayisenga-droid** [comment]
> This should be under the odkconvert repository instead of the FMTM one. :-)

I did open this PR [here](https://github.com/hotosm/odkconvert/pull/59)

**Pull request closed without merging**
