### PR TITLE
Added few FAQs for FMTM users and contributors

### PR DESCRIPTION
**Pull request by neelimagoogly**
As mentioned in #147 issue , I have added few FAQs .
@petya-kangalova and @rsavoye please review this.

### CODE REVIEW

**Comment by Ndacyayisenga-droid** [comment]
@neelimagoogly we done,
Thats nice work👏

**Comment by Ndacyayisenga-droid** [comment]
@neelimagoogly we done,
Thats nice work👏

**Comment by robsavoye** [comment]
Thanks for this, but can we make this a FAQ.md instead of putting it in the README.md ? FAQs are usually a standalone document

**Comment by neelimagoogly** [comment]
> Thanks for this, but can we make this a FAQ.md instead of putting it in the README.md ? FAQs are usually a standalone document

Yes , that is right. Now I have changed it and made two more commits in which I have put all FAQs inside a FAQ.md file . Please have a look . If you approve this and merge it then we can proceed adding a link to this in README.md and Wiki page.

**Comment by robsavoye** [comment]
Looks like a good start, thanks!

**Comment by neelimagoogly** [comment]
@all-contributors please add @neelimagoogly  for #173

**Comment by neelimagoogly** [comment]
@all-contributors please add @neelimagoogly  for documentation

**Pull request merged**
