### PR TITLE
added apscheduler

### PR DESCRIPTION
**Pull request by nrjadkry**

### CODE REVIEW

**Comment by nrjadkry** [comment]
@spwoodcock 
I just realized that date trigger adds a job in the appscheduler_jobs table it creates in the db and then removes it immediately.
This might be a small problem if we want to use this table for our usecase.

**Comment by spwoodcock** [comment]
Do we need to trigger on date? This is for scheduling things in the future.

I think our use case is just to be able to return the job id, so we can queue, cancel, or pause the job.

**Comment by nrjadkry** [comment]
@spwoodcock 
There are 3 different triggers in apscheduler.
1. Interval trigger: Schedules a job to run at fixed intervals.
2. Cron trigger
    Schedules a job based on a cron-like expression.
    Options: year, month, day, week, day_of_week, hour, minute, second: Specify the cron expression.
3. Date trigger.
    Schedules a job to run once at a specific date and time.

Date trigger is the best one for our use case, but it creates the job in the db and then removes it immediately after the job is started.

Are there any other triggers that I have missed?

**Comment by spwoodcock** [comment]
See #912

We decided not to proceed with this.

**Pull request closed without merging**
