### PR TITLE
Removed outline and task info from project/id endpoint

### LINKED ISSUE #935: UX: remove task info from projects/<id> endpoint, call separately
## Issue

Calling the project info endpoint can take over 20 seconds if there are a lot of tasks.

E.g. https://fmtm-api.naxa.com.np/projects/24

## Solutions

- I would be best to separate the task information from the project info:
  1) On first load, the project info endpoint should be fast, returning the project outline & quickly panning to the project area on the map.
  2) The task info should be gathered from the tasks API endpoints: https://fmtm-api.naxa.com.np/tasks/task-list?project_id=24
- Coordination is required for the frontend/backend (although if the frontend part is done first, then the task info removed from the project endpoint, this wouldn't disrupt anything):

**Frontend**: change to use two API calls, one for the project, allowing the pan to project area to happen first, then load the tasks in.

**Backend**: remove the task info from the project endpoint.

## Additional Context

The tasks are loaded gradually from the API, taking most of the time receiving the response instead of waiting for it:

image

Try and load the endpoint: https://fmtm-api.naxa.com.np/tasks/task-list?project_id=24
You can see the data slowly populating.

It would be interesting to see if we could populate the data on the map as it loads, instead of waiting for it all to load and displaying at the end.

### PR DESCRIPTION
**Pull request by Sujanadh**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Issue
- Fixes #935 

## Describe this PR

This changes removes the inherited `ProjectBase` schema model from `ReadProject` where only required fields are defined which excludes `outline_geojson` and `project_tasks`.

## Response

```
{
  "id": 54,
  "odkid": 1817,
  "author": {
    "username": "Sujan Adhikari",
    "id": 18427944
  },
  "project_info": {
    "name": "testing sujan ",
    "short_description": "a",
    "description": "a"
  },
  "status": 2,
  "xform_title": "buildings",
  "hashtags": [
    "#FMTM"
  ],
  "organisation_id": 1,
  "project_uuid": "f27c2c4d-4338-41a2-bacc-0945a23afb38",
  "location_str": "Kathmandu,Nepal"
}
```

## Checklist before requesting a review

- 📖 Read the FMTM Contributing Guide: <https://github.com/hotosm/fmtm/blob/main/CONTRIBUTING.md>
- 📖 Read the FMTM Code of Conduct: <https://github.com/hotosm/fmtm/blob/main/CODE_OF_CONDUCT.md>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

### CODE REVIEW

**Comment by spwoodcock** [comment]
It's fine to remove the tasks from the response on the backend, but that's a tiny part of the task in issue https://github.com/hotosm/fmtm/issues/935.

Most of the edits are on the frontend, where we need to load the project info first, then progressively load in task data as it's returned.

- The basic implementation needs coordination with the backend and frontend changes.
- A more complex implementation may require testing how to load in the task data progressively as it's returned, perhaps using something like StreamingResponse.

**Comment by Sujanadh** [comment]
Oh okay. Then fetching data in chunks rather than all at once in frontend must be the desired behaviour?

**Comment by spwoodcock** [comment]
Possibly! It's probably not worth optimising for now. Only the basic version is necessarily, then we can improve later.

**Comment by spwoodcock** [comment]
Closing for now - we will come back to this and coordinate with the frontend.

**Pull request closed without merging**
