### PR TITLE
Switch from npm to pnpm, webpack to vite

### LINKED ISSUE #882: Switch from npm -> pnpm
**Is your feature request related to a problem? Please describe.**
Not particularly, just would improve DX.

**Describe the solution you'd like**
Switch from NPM to PNPM, and then tweak the associated docker scripts.

**Describe alternatives you've considered**
I suppose Yarn and Bun are alternatives, but on the whole PNPM is more performant than Yarn, and from experience is more reliable too. And for Bun, I don't believe it's quite prod ready yet, although I'd say it's 100% something we can look forward to using in the future. 

**Additional context**
N/A

### LINKED ISSUE #883: Switch from webpack -> vite
**Is your feature request related to a problem? Please describe.**
Switch from using webpack to vite, it's so so much quicker, less config required and has quite a few other benefits.

**Describe the solution you'd like**
Switch from webpack -> vite.

**Describe alternatives you've considered**
Not really any I can think of at the moment.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by JoltCode**
Closes #882, closes #883

### CODE REVIEW

**Comment by spwoodcock** [comment]
Please change the base branch from main --> development. 

In the future we may make this the default branch, but for now we have to manually change on each PR.

Thanks!

**Comment by JoltCode** [comment]
> Please change the base branch from main --> development.
> 
> In the future we may make this the default branch, but for now we have to manually change on each PR.
> 
> Thanks!

Ohh will do! 👍

**Comment by JoltCode** [comment]
Thanks! 😄

**Comment by spwoodcock** [comment]
Looks like you branched from main at the start - sorry it's not very clear that we do all development and merging with the `development` branch.

This is a good prompt that we should probably clarify the process a bit better in the docs.

To fix this PR, you can either rebase: `git rebase development` and fix conflicts. 

Or easier may be to make a new branch and cherry pick your commits there 👍

**Comment by spwoodcock** [comment]
Also you probably noticed the CI triggering on each push, so it may be better to push in batches of that's ok

**Comment by JoltCode** [comment]
> Looks like you branched from main at the start - sorry it's not very clear that we do all development and merging with the `development` branch.
> 
> This is a good prompt that we should probably clarify the process a bit better in the docs.
> 
> To fix this PR, you can either rebase: `git rebase development` and fix conflicts.
> 
> Or easier may be to make a new branch and cherry pick your commits there 👍

No worries! Yeah I did a merge and tried to solve the conflicts, seems I messed up the backend folder though... Just trying to sort that at the moment :)

**Comment by JoltCode** [comment]
> Also you probably noticed the CI triggering on each push, so it may be better to push in batches of that's ok

Yep 👍

**Comment by JoltCode** [comment]
ughh :(

**Comment by JoltCode** [comment]
There we go! 😄

**Comment by JoltCode** [comment]
(sorry have still been doing quite a few individual pushes, just was trying to sort my git tree) :)

**Comment by JoltCode** [comment]
Should be ready for a review now @spwoodcock 🎉 - I also migrated the frontend testing from Jest -> Vitest - seemed Vite just didn't want to play ball with Jest, and thought may as well move to Vitest while I'm at it with the Vite migration.

**Review by spwoodcock — APPROVED** [review]
Nice PR - great stuff - I will do a build and test tomorrow and merge in 👍

**Comment by JoltCode** [comment]
> Nice PR - great stuff - I will do a build and test tomorrow and merge in 👍

Perfect thanks!

**Comment by JoltCode** [comment]
Closes #882, closes #883

**Comment by spwoodcock** [comment]
@all-contributors add @JoltCode for code

**Pull request merged**
