### PR TITLE
proper link to get started

### PR DESCRIPTION
**Pull request by Roseford**

### CODE REVIEW

**Review by spwoodcock — CHANGES_REQUESTED** [review]
Thanks @Roseford! Please could you change the link text from `Documentation` to `Getting Started` then we can merge

**Comment by Roseford** [comment]
You mean from *Development* to * Getting Started* Right?

**Comment by spwoodcock** [comment]
Sorry, yes I do

**Comment by spwoodcock** [comment]
Thanks for the update

**Review by spwoodcock — APPROVED** [review]

**Comment by Roseford** [comment]
Hi @spwoodcock, 
I am having some issues setting up the backed fmtm app without Docker on my local computer, please if know how to do this, can I get a quick run down on the steps to follow?

**Comment by spwoodcock** [comment]
I could say use Docker, as you need two databases running, plus ODKCentral.

If you already have a version of ODKCentral running, with credentials, then you could:

1. Start the FMTM database: `docker compose up -d fmtm-db`
2. Install depdependencies
```bash
pip install pdm
cd src/backend
pdm install
```
3. Change FMTM_DB_HOST in .env to localhost:5432
4. Start the API: 
```bash
cd ..
uvicorn backend.main:api --reload
```

If you get it working, please update the docs.

**Pull request merged**
