### PR TITLE
Add links to Git & Docker in INSTALL.md

### PR DESCRIPTION
**Pull request by khushishikhu**
Added the links to redirect github and docker. So the new contributors would know about these technologies

### CODE REVIEW

**Comment by spwoodcock** [comment]
Thanks for the contribution @khushishikhu!

Just to clarify, GitHub is not synonymous with Git.
GitHub is just an online platform that hosts Git repositories, while Git is the actual source control management tool for code.
The correct URL for Git would be https://git-scm.com 👍

**Comment by khushishikhu** [comment]
@spwoodcock Sure, I have updated the doc with the correct link

**Comment by spwoodcock** [comment]
So sorry to be difficult 😅 
I updated the base branch to be `development`, as we should make all PRs from feature --> development.
Could you possibly rebase your branch? Or the easier thing to do would be:

- Copy your edits to a temp file.
- Run the following.
```bash
git checkout development
git reset --hard origin/development
```
- Copy your edits on top and make new commits.

**Comment by khushishikhu** [comment]
@spwoodcock I will make another PR, would be less complicated. I have updated my branch

**Pull request closed without merging**
