### PR TITLE
Mapper frontend login + remove temp auth from React frontend

### PR DESCRIPTION
**Pull request by NSUWAL123**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue
- Related to #1890

## Describe this PR
This PR contains the following works: 
**Mapper Frontend**
- OSM and Temp login add to mapper frontend
- Remove Temp login from react frontend
- Change hot-header component with custom header component with drawer

**React Frontend**
- Replace Legend Toggle to map control component
- Add button named `START MAPPING` to link react frontend to mapper frontend

## Screenshots
image
image
image
image

### CODE REVIEW

**Comment by NSUWAL123** [comment]
Oh, the frontend test is failing as we had used a temp login for the playwright test. Now what shall be the alternative? 

Creating an OSM account to conduct the e2e test? Would that be feasible?

**Review by spwoodcock — APPROVED** [review]
This is excellent!

The only thing missing is the cookie refresh behaviour. On first load the refresh endpoint should be called to attempt cookie refresh (and extend it's expiry). The react frontend does this.

Perhaps it can be a follow up PR, as this is great to merge 😄

**Comment by spwoodcock** [comment]
> Oh, the frontend test is failing as we had used a temp login for the playwright test. Now what shall be the alternative? 
> 
> Creating an OSM account to conduct the e2e test? Would that be feasible? 

Also good point!

I will hold off from merging and look at playwright options for login 👍

Could you look at the refresh action?

**Comment by NSUWAL123** [comment]
Sure!

**Comment by NSUWAL123** [comment]
@spwoodcock the /refresh endpoint called on the first load on mapper frontend has already been implemented by you. 
You were mentioning this right? or I am confused.
image

**Comment by spwoodcock** [comment]
Yes that's the one!
I must have forgot 😅 
Looks like we are set then!
(I'll just fix up the playwright stuff tomorrow then merge)

**Pull request merged**
