### PR TITLE
Update build and deploy workflows using build args + Github Container Reg

### LINKED ISSUE #119: Remove localhost entries from production CORS origins
Currently the API server for https://fmtm-api.hotosm.org manually override the BACKEND_CORS_ORIGINS list in the `.env`, to aid development:

```
BACKEND_CORS_ORIGINS=https://test.fieldmappingtm.org,https://fieldmappingtm.org,http://localhost:8080,http://localhost:8081
```

This must be removed when the system goes into production, as it is bad security.
The variable can be removed completely, as the origins for the frontend are added automatically.

### LINKED ISSUE #284: Create staging deployment workflow using generic docker setup
### Currently we have
- A local development setup, by using the docker-compose.yml and a .env.
- A development server: currently this uses docker-compose.prod.yml with some hardcoded/tweaked variables on the server. @mahesh-naxa has more details on this.
  - Ideally we should deploy this in the same way as prod, by using the checked out repo branch, instead of a repo that is located on the server itself (preventing file permission conflicts, or git conflicts during pull of the `development` branch.
- A production server: which uses docker-compose.prod.yml, including some hardcoded values (domains) in the compose file.

### Proposed setup
- Keep the local development `docker-compose.yml` as it is - works nicely.
- Three separate docker-compose files/configs (required for now to hardcode domain names for traefik)
  - `deploy/docker-compose.dev.yml` (excludes local ODKCentral, uses a standalone version for testing)
  - `deploy/docker-compose.stag.yml` (includes local ODKCentral)
  - `deploy/docker-compose.prod.yml` (includes local ODKCentral)
- Each config will have an environment set on Github, including a secret .env variable that is injected on deploy.
- Each config will have a Github action associated for the deploy (they should be identical, just with different secrets).
- Each config should use it's own image tags. E.g. fmtm:main, fmtm:development, fmtm:staging

### Prerequisite
- Create a staging branch in the repo.

### Note
- The traefik setup currently blocks us creating a generic docker-compose for deployment (regex to remove `https://` doesn't work).
- We may be able to simplify this setup by changing API_URL, FRONTEND_MAIN_URL, FRONTEND_MAP_URL to API_DOMAIN, FRONTEND_MAIN_DOMAIN, FRONTEND_MAP_DOMAIN (forgotten if I already tried this & was blocked by something...).
- The domain vars can then be used for traefik variable injection and `http://` or `https://` prepended to their use requiring the protocol. We could also create a FRONTEND_PROTOCOL variable to specify and inject `http`:// or `https`://.
- This would result in:
`docker-compose.yml` local dev
`docker-compose.deploy.yml` for staging and prod, with env var injection
`docker-compose.noodk.yml` for dev deploy, with env var injection (remove all odkcentral services)

### PR DESCRIPTION
**Pull request by spwoodcock**
Fixes #284 #192 #376 #377
Updating config will also fix #119

This PR significantly improves the image build and deploy workflows, due to using Github Container Registry instead of Quay.io.

## IMPORTANT
There are some minor changes to the .env file unfortunately (could not be avoided).
**Extra**: URL_SCHEME
**Modifed**: API_URL, FRONTEND_MAIN_URL, FRONTEND_MAP_URL

We now need:
```dotenv
### FMTM ###
URL_SCHEME=http
API_URL=127.0.0.1:8000
FRONTEND_MAIN_URL=localhost:8080
FRONTEND_MAP_URL=localhost:8081
```
> Note: the URL for each service does not contain the scheme.

## TODO (DONE 🏁)
- Finish workflows 🏁 
- Update DOT_ENV vars for each environment 🏁 
- Inject build args for version labels, extracting from `pyproject.toml` and `packages.json` 🏁 
- Update Python dependency management to PDM 🏁

### CODE REVIEW

**Comment by spwoodcock** [comment]
### Update

**Versioning**
As part of this refactor I will also tackle #192, giving us versioning for the container images.

**Removing ODK Central**
After discussion with the team, we no longer require the ODK Central backend to be part of the deployment stack, as every project created in FMTM requires an external ODK Central URL to be provided.

I will strip this out for the dev,staging,prod deploy configs.

I will, however, keep the config for the main `docker-compose.yml` which is used for debugging (it will save time for the developer to get started immediately).

**Comment by spwoodcock** [comment]
Will also solve #376 and #377 in this PR.

**Comment by robsavoye** [comment]
I notice that now when I approve a PR, I get an error from github about the deployment.

**Comment by spwoodcock** [comment]
What is the error? It can't be related to this PR, as we haven't merged yet. Message me details on slack 👍

**Comment by spwoodcock** [comment]
This PR should be done.

The main additions are:
- Python 3.10.
- Backend dependency solving using PDM.
- Version control for frontend and backend, including image naming.
- Dynamic variable injection during frontend build and deploy (hostnames for each microfrontend).
- Using Github Container Registry over Quay.io. This simplifies the Github actions.
- New consolidated Github actions to be more maintainable and to be exactly the same for prod/staging/dev.
- Image builds within the Github actions --> triggering deploy via built images (instead of building on the servers themselves).

It finished all mentioned issues, and also includes some minor fixes to the backend (particularly around the credentials used for ODK Central).

By default credentials should be passed explicitly when calling using classes from `osm-fieldwork`. But it can also fall back to using environment variables to connect. This could be refactored in future to be handled entirely by `osm-fieldwork` instead of in FMTM.

I updated the Github configs required for this too:
- **main** and **development** environments, which are used for the `main` and `development` branches.
- Environment variables in each app environment: `DOCKER_HOST`, `SSH_PRIVATE_KEY`, `DOTENV`.

As mentiond, the new Github workflows attempt to consolidate the config into a single workflow to handle prod/staging/dev.
However, it's difficult to test Github workflows offline.
**The Github workflows may require further testing after deploy and fixing**.

**Comment by robsavoye** [comment]
Can you fix the failing pytest and the conflicts ? I tested this branch locally and it worked fine.

**Comment by spwoodcock** [comment]
Fixed 👍

The pytest test is not fixable as this PR edits the workflow itself (to work with PDM).
But it should be working again after merge.

**Pull request merged**
