### PR TITLE
Upload template files to s3

### PR DESCRIPTION
**Pull request by Sujanadh**
fixes: #1002 
Created an api to upload template files. Template file names are made static so that every time new template is uploaded it will replace the existing file .

### CODE REVIEW

**Review by spwoodcock — COMMENTED** [review]
The template path should be nested under the org and the project.

I would say the path should be:
`f'{org_id}/{project_id}/form.xls`

As for the data extracts, they won't be stored in our S3 bucket.
Please see #934
A link to the extract is stored in our DB, but the extract file itself will be stored externally in flatgeobuf format.

**Comment by nrjadkry** [comment]
This is just a template for the users wanting to upload a custom data extracts.
Custom data extracts requires `title` field in the properties and few more of them. If the user misses those fields, odk collect throws an error. I have kept an empty title field for those features without the title field from the code. But, providing the user with the template and allow them to view the format they require might be better.

**Comment by nrjadkry** [comment]
Yes, you are right. API is actually not required here. We can do this just through a simple python script.
I wanted to confirm you with the templates folder structure in S3.

@Sujanadh , It might be better to use python script rather than these unauthenticated apis.

**Comment by spwoodcock** [comment]
The easiest place to put it for now is probably:

`backend/app/static` (make the dir)

Then we can serve any static files we have from an endpoint.

The endpoint could be e.g. `/template` and it returns a File response of the template file.
The frontend can then use it too.

**Comment by Sujanadh** [comment]
so i should just change the endpoint and return file response from `static` dir ?

**Comment by Sujanadh** [comment]
@spwoodcock @nrjadkry

**Review by spwoodcock — COMMENTED** [review]
Nice, looks good 👍

**Pull request merged**
