### PR TITLE
Configure pytest to work with github workflow

### PR DESCRIPTION
**Pull request by spwoodcock**
Partially completes #76 (backend).
Frontend testing via workflows still required.

### CODE REVIEW

**Comment by spwoodcock** [comment]
Hold on merging this, I need to make the tests work first!

**Comment by spwoodcock** [comment]
PyTest should now work.
The problem is that the tests are all broken (starting from the conftest.py).
I'll create a separate PR fixing the tests.

**Comment by spwoodcock** [comment]
Looks like from the latest run this fixed the issue.
The error is related to the broken test (instead of missing the pytest dependency).

**Comment by spwoodcock** [comment]
- I also tacked onto this PR a commit that removed the old tests - they were all for the demo flask frontend & were failing.
- The PyTest workflow should now pass - I added a dummy test to make it work.

**Comment by spwoodcock** [comment]
- There was a project.listProjects() called during app startup - attempting to call the odkcentral server & making tests fail - removed it.
- Partial implementation of #69 instead (not fully tested).

**Comment by robsavoye** [comment]
There's a conflict with this patch.

**Comment by spwoodcock** [comment]
Fixed - was due to the cors origins update.

**Pull request merged**
