### PR TITLE
Update auth cookie logic for both backend and frontend (seamless temp auth)

### PR DESCRIPTION
**Pull request by spwoodcock**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation
- [x] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue

Follow on from https://github.com/hotosm/fmtm/pull/1948

## Describe this PR

- This is the final things to fix prior to new release 2024.5.0.
- Please check over all of my logic & test this thoroughly @Sujanadh @Anuj-Gupta4 @NSUWAL123 @manjitapandey 
- I haven't thoroughly tested this yet, as I planned to merge early and test more easily on dev. It's also getting late for me, so I though it best to just push and let you all help me find errors too!

**Content**

- I removed the 'Temporary Login' card / option from the mapper frontend.
- Now the login is handled seamlessly: if the user is not logged in, they are provided a temporary token/cookie.
- If the user logs in via OSM, they overrides the temp token (temp cookies are revoked).
- We should update at some point to inform the user of this:
  - First load of mapper frontend, we have a localStorage key / prompt.
  - If the user is not signed in via OSM, we say: 'You are not signed in via OSM. If you wish for your mapping contributions to be linked to your profile, please log in first'.
- I made the logic a bit more DRY on the backend.
- The refresh endpoints refresh both cookies, but also return the user details JSON.

## Review Guide

Notes for the reviewer. How to test this change?

## Checklist before requesting a review

- 📖 Read the FMTM Contributing Guide: <https://github.com/hotosm/fmtm/blob/main/CONTRIBUTING.md>
- 📖 Read the HOT Code of Conduct: <https://docs.hotosm.org/code-of-conduct>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

### CODE REVIEW

**Comment by spwoodcock** [comment]
On refresh, the json payload was not returning with AuthUser correctly:

image

Added commit https://github.com/hotosm/fmtm/commit/3a9a50f9d94822101233164f233b8af908c54b38 to address this, now deploying.

Heading to bed, but hopefully it works 🤞 😴

**Comment by Anuj-Gupta4** [comment]
image


cant use mapper frontend after clearing cookies

**Comment by spwoodcock** [comment]
I think the above issue is related to the ones you fixed @Anuj-Gupta4 , but would you be able to double check its not a separate issue? 🙏

**Comment by Anuj-Gupta4** [comment]
It is the same issue. We changed the code to use separate db pool connection for updating the background task status.

**Pull request merged**
