### PR TITLE
Created Project dashboard

### PR DESCRIPTION
**Pull request by Sujanadh**
# Updates
This PR introduces the `get_dashboard_detail` async function, which fetches project details for the project dashboard using `project_id`. 
### Response
{
  "project_name_prefix": "test sujan",
  "organization": "naxa",
  "organization_logo": "http://s3.fmtm.localhost:7050/fmtm-data/1/logo.png",
  "total_tasks": 6,
  "total_submission": 0,
  "total_contributors": 2,
  "created": "06 Dec 2023",
  "last_active": "6 days ago"
}

### CODE REVIEW

**Review by spwoodcock — APPROVED** [review]
Nice using the pydantic schemas 👍

**Comment by varun2948** [comment]
@spwoodcock what are we using nowonwards ? pydantic schemas or raw sql ? Cause i see at some part of code we are using pydantic and some part has raw sql. Shouldn't it be uniform on all part of code or am i missing something ?

**Comment by spwoodcock** [comment]
Hi @varun2948, you raise a good point!
Although I think you must mean SQLAlchemy models vs raw SQL.

Pydantic schemas are used for JSON serialization to and from SQLAlchemy database models.

That plan was (and still possibly is) to refactor out SQLAlchemy in favour of raw SQL.
But until there is time to do that, we can use either raw SQL or the SQlAlchemy models (with raw SQL being preferred if possible).

**Comment by varun2948** [comment]
Oh yeah i meant SQLAlchemy vs raw SQL :smile: okay sounds good @spwoodcock Thanks

**Pull request merged**
