### PR TITLE
Fix dynamic submissions legend chloropeth

### PR DESCRIPTION
**Pull request by NSUWAL123**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Describe this PR
This PR comprises the following works done:
1. Dynamic min max value for tasks map legend and task choropleth
2. Popup add on task click displaying taskID, expected and submission counts

## Screenshots
image

### CODE REVIEW

**Comment by NSUWAL123** [comment]
@spwoodcock, resolved the conflicts. Its ready to be be merged. 

> Recently I bound a modal to data extract geometries on click, so if you could check there isn't a conflict between the modal and popup it would be ideal =) 
 I didn't understand what you said. Could you elaborate?

**Comment by spwoodcock** [comment]
When you click the task the info popup shows.

The buildings (data extract) for the task area also load and display.

When if you click one of those loaded buildings, a modal will pop up giving the OSM details for the feature.

You may have to try this in a newly created project to see it all working.

I just wanted to check there is no conflict between these functionalities (I think the click priority is handled by the zindex)

**Comment by spwoodcock** [comment]
Project creation should be fixed on the latest develop, so if you get an error please submit a bug report 😄

**Comment by spwoodcock** [comment]
I realised I added the code I mentioned above to `NewProjectDetails.jsx`, but we are now using `ProjectDetailsV2.tsx` 😅 

I will merge this, then add my code back in.

When you get time @NSUWAL123 could you remove any old components that are not used please? 🙏 
It's difficult to know where code should belong for me, so it would be especially difficult if we had an external contributor too.

**Pull request merged**
