### PR TITLE
Update User-Manual-For-Project-Managers.md

### PR DESCRIPTION
**Pull request by manjitapandey**
## What type of PR is this? (check all applicable)

- [x] 📝 Documentation

## Related Issue

Related: https://github.com/hotosm/fmtm/issues/921

## Describe this PR

This PR updates the project creation workflow documentation and addition of recently developed features which weren't there in user manual. 

## Review Guide

Notes for the reviewer. How to test this change?

## Checklist before requesting a review

- 📖 Read the FMTM Contributing Guide: <https://github.com/hotosm/fmtm/blob/main/CONTRIBUTING.md>
- 📖 Read the HOT Code of Conduct: <https://docs.hotosm.org/code-of-conduct>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

### CODE REVIEW

**Comment by spwoodcock** [comment]
@allcontributors add @manjitapandey for docs

**Comment by spwoodcock** [comment]
@allcontributors add @susmina94 for docs ideas bug reports
add @manjitapandey for ideas

**Comment by spwoodcock** [comment]
@allcontributors add @manjitapandey for ideas

**Comment by spwoodcock** [comment]
@allcontributors add @manjitapandey for ideas

**Comment by spwoodcock** [comment]
@allcontributors add @Sujanadh for maintenance

**Comment by spwoodcock** [comment]
@allcontributors add @NSUWAL123  for maintenance

**Comment by spwoodcock** [comment]
@allcontributors add @NSUWAL123 for maintenance

**Comment by spwoodcock** [comment]
Sorry for all the spam Manjita - I had to do this somewhere 😅 
I hate this all-contributors bot - it's so messy!

**Comment by nrjadkry** [comment]
@manjitapandey pre-commit has failed in this pull request. 
You can apply following commands to resole this.
```
pip install pre-commit
pre-commit install
pre-commit run --all-files
```

**Pull request closed without merging**
