### PR TITLE
Prevent project generation if api failure

### PR DESCRIPTION
**Pull request by spwoodcock**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Describe this PR

- Currently if there is a failure with of the 4 project creation APIs, the creation will continue, and redirect.
- Instead it should halt creation and display an error to the user.
- I did some refactors here @NSUWAL123 to use a state variables: `generateProjectError` and `generateProjectSuccess`.
- If `generateProjectSuccess` is set to true, then the watcher in `SplitTasks.tsx` will display a success message and do the redirect.
- If `generateProjectError` is set at any stage, then the remaining project creation stages should stop - I didn't get to implement this, could you take a look please?
- It might be a good idea to add the project creation and data extract upload to separate services, for consistency.

## Review Guide

Notes for the reviewer. How to test this change?

## Checklist before requesting a review

- 📖 Read the FMTM Contributing Guide: <https://github.com/hotosm/fmtm/blob/main/CONTRIBUTING.md>
- 📖 Read the HOT Code of Conduct: <https://docs.hotosm.org/code-of-conduct>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

### CODE REVIEW

**Review by NSUWAL123 — APPROVED** [review]

**Comment by NSUWAL123** [comment]
@spwoodcock, what approach can we take in this scenario: 
there are 4 api's called on project creation. Say that if the 1st API (/create-project) is successful but the second API fails and we halt the project creation. Though it seems that the project creation step is halted, a project is created. 

image
Here, only the first API is called and the project is created. Should we call delete project API if there's error on project creation displaying error or only display error?

**Comment by spwoodcock** [comment]
I think that's a very good idea 👍

Call delete project so the user can try again

**Comment by spwoodcock** [comment]
I merged the other PR then rebased this to `development`.

It should only include the edits made 🙏

**Comment by spwoodcock** [comment]
Working nicely for me! Great job Nishit 🎉

**Pull request merged**
