### PR TITLE
Mapper navigation mode integration

### PR DESCRIPTION
**Pull request by NSUWAL123**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue
- Related to #1888

## Describe this PR
1. Geolocation dot and orientation arc by default when the page loads
2. A separate button to go in 'navigation mode':
- The orientation arc is replaced with an arrow
- The map pitches to an angle of 50 degrees.
- The map rotates to match the user's device orientation, with the arrow at the center of the screen all the time.

## Screenshots
https://github.com/user-attachments/assets/46de1388-2ba3-4de5-9be8-0c87d6482c5e

### CODE REVIEW

**Comment by NSUWAL123** [comment]
Any suggestions on displaying the `navigate` button better in terms of UX?  @spwoodcock @manjitapandey

**Comment by spwoodcock** [comment]
Love it!

Instead of a general button on the map for navigation mode, could it be a button we click on the feature popup?

We can have two buttons 
'Navigate Here'
'Map In ODK' --> 'Collect Data'

For now, it just enables navigation mode.
In a future PR, it also displays the walling route.

Does that sound OK?

**Comment by spwoodcock** [comment]
Also I realise we need a way to disable navigation mode in this case too:

- A button overlaying the map to say 'Stop Navigation'
- When the user clicks 'Collect Data' to go to ODK, we also stop the navigation before the redirect

**Comment by NSUWAL123** [comment]
Yeah! Sounds good

**Pull request merged**
