### PR TITLE
Implement comprehensive test coverage for the Create Project API and related functions

### PR DESCRIPTION
**Pull request by Sujanadh**
This pull request adds test cases to verify the functionality of project creation and associated functions. The tests include creating a project via the "create_project" API, handling ODK Central project creation, converting database projects to application projects, and uploading custom data extracts for tasks.
The test cases cover various aspects of project creation, data handling, and integration with external services.
Key test areas covered include:
- Project creation with various parameters.
- ODK Central project creation.
- Converting database project objects to application-specific representations.
- Uploading custom data extracts for project tasks.

### CODE REVIEW

**Comment by spwoodcock** [comment]
Looking into this now, long overdue! Thanks @Sujanadh 🥇 

I have given you write access to the repo for the future, so you can create branches directly, instead of making PRs from your fork.

This will allow me to more easily update your branch / commit on top.

One thing I noticed immediately is that we have a 3MB geojson in test data. Could this be reduced in size at all?
Each MB we add to the repo slows down the clone time for others.

**Comment by nrjadkry** [comment]
@spwoodcock pytest can not find the tests written in the backend/tests/ in the local development.
@Sujanadh has told me that he has written tests inside of the backend/app/tests/ in his local development and then migrated them to the backend/tests/. He is using docker for the local development too.

**Comment by robsavoye** [comment]
we could compress the GeoJson file.

**Comment by spwoodcock** [comment]
Closed in favour of #900

**Pull request closed without merging**
