### PR TITLE
Backend tests for project endpoints

### LINKED ISSUE #169: Create test cases for backend API
Currently FMTM lacks working test cases. Ideally every endpoint should have unit level test case.

### PR DESCRIPTION
**Pull request by Sujanadh**
Fixes #169

This pull request contains the updated test data within a compressed zip file. It encompasses all the modifications made in my previous pull request, which was PR #870 in the forked repository. We can close the old pull request.

### CODE REVIEW

**Comment by spwoodcock** [comment]
Thanks @Sujanadh! I will review this tomorrow 👍

Quick note: I think the `test_data` dir should go under `tests` not `app` in the backend dir.

**Comment by robsavoye** [comment]
I think it does need to be called tests, and be more top level so pytest works. Btw, thank you for adding tests! This is something FMTM is seriously lacking, so every little bit helps.

**Comment by spwoodcock** [comment]
Also, check the failing tests in the pytest run - they are showing valid errors.
E.g. the file `/opt/app/test_data/building_footprint.zip` is missing from the PR.

**Comment by nrjadkry** [comment]
@spwoodcock pytest does not find the tests written outside the app directory. We might need to fix that to write the tests outside of app directory.

**Comment by spwoodcock** [comment]
The issue with not finding the test data is because of the github workflow.
When the pytest container runs, the repo is checked out to a directory that isn't /opt (as with our normal container build). The path needs to be relative within the repo, not an absolute file path 👍

**Comment by spwoodcock** [comment]
This PR is complete for the actual tests - thanks guys!

The only remaining thing (for me) to do is update the r-pytest.yml workflow.

I won't go into it much, but in summary the tests fail currently as their is a networking issue FMTM --> ODK Central on the Gitlab runner that I need to fix.
(it wasn't an issue before, as we didn't use the ODK Central container in our tests)

**Comment by spwoodcock** [comment]
The tests were not working as expected on a fresh database.

They worked fine when a project already existed in your db, but after running `docker compose down -v` and deleting the db, the tests fail.

I fixed the conftest setup.
I was just debugging the final create appuser files test.

@Sujanadh if you could possibly look into this, it would be a big help 🙏
It's very close to being done, I just have to catch a flight now to be in a closer timezone to you guys.

**Comment by Sujanadh** [comment]
@spwoodcock  sure , i will look into this.

**Comment by Sujanadh** [comment]
@spwoodcock i think it might need separate test database which will be created and deleted after test execution. 
It seems that our test cases are working fine as long as we use a project ID that doesn't exist in our database. However, when we use an existing project id , in my case i have project with project_id 123 which is used in our conftest,  test fails to create an appuser.

**Comment by Sujanadh** [comment]
@spwoodcock i think we should use separate test database not the fmtm-db , when i created project in my local production, it generated project_id following project_id generated from the test case.
ps: i am still debugging create_app user, i tried using different project_id , it worked for some (eg:project_id:1233). 
separate test db might solve this??

**Comment by spwoodcock** [comment]
Hi @Sujanadh, we should definitely use a fresh database for tests 👍 

The way the github workflow functions:
- Set up all the containers from docker-compose.yml (including a fresh db)
- Run the tests in the api container (fastapi backend, including all dependencies).

The way I replicate this on my machine:

```bash
# Use the tag override variable to use the ci image - including all test dependencies too
API_TAG_OVERRIDE=ci-development dc up -d api

# Exec into the fmtm container
docker compose exec api bash

# Run tests
pytest

# Exit and delete the database if needed
exit
docker compose down -v
# You can then run from the start again
```

The error I am getting for creating appuser:

```
2023-10-17 05:51:15.016 | DEBUG    | app.projects.project_crud:upload_custom_data_extracts:1186 | Generated project geojson: {"type":"Polygon","coordinates":[[[8.539551724,47.376578892],[8.539551724,47.373032474],[8.547135285,47.373032474],[8.547135285,47.376578892],[8.539551724,47.376578892]]]}
2023-10-17 05:51:15.488 | INFO     | app.projects.project_crud:generate_task_files:1263 | Generating files for task 1
2023-10-17 05:51:15.489 | INFO     | app.projects.project_crud:generate_task_files:1271 | Creating app user for task 1
2023-10-17 05:51:15.489 | Level 10 | osm_fieldwork.OdkCentral:__init__:139 | ODKCentral configuration parsed: https://central-proxy
2023-10-17 05:51:16.559 | Level 10 | urllib3.connectionpool:_new_conn:1048 | Starting new HTTPS connection (1): central-proxy:443
2023-10-17 05:51:16.788 | Level 10 | urllib3.connectionpool:_make_request:546 | https://central-proxy:443 "POST /v1/projects/123/app-users HTTP/1.1" 404 76
2023-10-17 05:51:16.789 | INFO     | app.central.central_crud:create_appuser:181 | Created app user: {'message': 'Could not find the resource you were looking for.', 'code': 404.1}
2023-10-17 05:51:16.789 | ERROR    | app.projects.project_crud:generate_task_files:1276 | Couldn't create appuser for project
```

**Comment by spwoodcock** [comment]
@Sujanadh we weren't making the odkcentral project prior to the fmtm project - fixed in latest push.

Just debugging the last error in task creation now:

```
2023-10-17 06:28:45.961 | DEBUG    | app.tasks.tasks_crud:convert_to_app_task:237 | Project ID 8 | Task ID 6 | Converting DB Task to App Task
2023-10-17 06:28:45.961 | DEBUG    | app.tasks.tasks_crud:convert_to_app_task:241 |
2023-10-17 06:28:45.961 | DEBUG    | app.tasks.tasks_crud:convert_to_app_task:254 | Converting task outline to geojson
2023-10-17 06:28:45.962 | WARNING  | app.tasks.tasks_crud:convert_to_app_task:269 | No QR code found for task ID 6
------------------------------------------------ Captured log call ------------------------------------------------
DEBUG    osm_fieldwork.OdkCentral:OdkCentral.py:139 ODKCentral configuration parsed: https://central-proxy
DEBUG    urllib3.connectionpool:connectionpool.py:1048 Starting new HTTPS connection (1): central-proxy:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://central-proxy:443 "POST /v1/projects/1/app-users HTTP/1.1" 200 343
-------------------------------------------- Captured stderr teardown ---------------------------------------------
2023-10-17 06:28:45.981 | INFO     | app.projects.project_crud:generate_task_files:1348 | Generating xform for task 6
============================================= short test summary info =============================================
FAILED tests/test_projects_routes.py::test_generate_appuser_files - KeyError: '\\x00\\x00\\x00|\\x00\\x00\\x00'
1 failed, 5 deselected in 3.81s
```

**Comment by spwoodcock** [comment]
Fixed.

Finalising an edit to the Dockerfile, then will merge this.

**Comment by Sujanadh** [comment]
Thank you, @spwoodcock, for the clear explanation. That explains the cause of error well.

**Comment by spwoodcock** [comment]
Damn gh-workflows can be annoying 😆 
Sorry for all the spam everyone - this is finally done.

Workflows didn't seem to support a simple feature like using docker compose service aliases correctly.
Turns out it was a missing env var CENTRAL_DB_HOST, which defaults to `postgres14` (and should be `central-db`).
Updated the default.

**Pull request merged**
