### PR TITLE
Added a validator to check for valid custom tms url

### PR DESCRIPTION
**Pull request by Sujanadh**
## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue

- Issue #1719 

## Describe this PR

This PR adds a field validator to check for the valid custom tms url. These changes checks for the:
- valid place holders such as `{z} {x} {y}` return exception if there are any invalid place holders for example, space in `{ z}`
- checks for valid file extensions such as `['png', 'jpg', 'jpeg', 'tiff', 'webp', 'pbf']` so it will raise exception if invalid extension such as `.json`
- raises `HTTPException` if any error besides above conditions

## Screenshots

N/A

## Alternative Approaches Considered

Did you attempt any other approaches that are not documented in code?

## Review Guide

Try creating project with invalid tms url it will raise error at the last step when create project is submitted.

## Checklist before requesting a review

- 📖 Read the FMTM Contributing Guide: <https://github.com/hotosm/fmtm/blob/main/CONTRIBUTING.md>
- 📖 Read the HOT Code of Conduct: <https://docs.hotosm.org/code-of-conduct>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

### CODE REVIEW

**Review by spwoodcock — CHANGES_REQUESTED** [review]
Nice!

TMS URL format is very variable though, and the {x} {y} {z} placeholders are not actually mandatory 😆

The file extension is also entirely optional, but if included it's good to check it's a valid one 👍

This is a good final check to avoid errors, but ideally we also need to pair with frontend validation too for real time user feedback if there are issues (better user experience)

**Comment by spwoodcock** [comment]
In osm-fieldwork there is a basic regex to strip the {x} {y} {z}

Perhaps that could be updated to be more flexible and strip { x} too (if possible)

**Comment by Sujanadh** [comment]
in case of file extension i have just added couple of extensions to check if user provides false extension , if no extension is provided it won't check for extension validation as url may not always have extension so it works and checks for the place holders.

Can you explain me what things should be checked for a valid tms url?

**Comment by Sujanadh** [comment]
what do you think validation should be in fmtm or osm-fieldwork ?
And yes we need validation in frontend for the real time user experience

**Comment by spwoodcock** [comment]
Ideally the backend validation should probably be in osm-fieldwork, with the frontend validation done in FMTM 👍 

I'm open to ideas on the criteria to validate a TMS URL.
But honestly it may not be possible.

If we were provided a URL like: `https://someserver.com/mytiles/15/444/333.png`, then we could validate the structure of the final part of the URL {num 0-24}/{num}/{num}

But as we get a URL more like this: `https://someserver.com/mytiles/` or `https://someserver.com/mytiles/{z}/{x}/{y}` then there is no good way I can think of to validate this, other than extracting the tile image format from an extension like `.png` and removing the `{z}/{x}/{y}` from the URL.

A good start would be to make the regex more flexible in osm-fieldwork so that `{ z}/{x   }/{ y}` won't break it

**Comment by Sujanadh** [comment]
we won't get number in the URL, so whats the point of checking {num 0-24}/{num}/{num} it is only generated when creating tiles for different zoom level. Ideally, we can only check if there are place holders for x y z we can check {   x} and validate it. in terms extension should we check it? if it is valid or not?

**Comment by spwoodcock** [comment]
Sorry my message above wasn't clear - that's what I meant 😄

I was giving an example 'if we got the URL in this format, then we could...'. But we don't get the URL with actual grid coordinates, so we can't check that!

As you say, we should check for and remove any placeholder values, if present. 

They will mess up the download if any of the placeholder remains

**Comment by spwoodcock** [comment]
And yea to your last question 👍

If there is an extension present, validate it & then remove it (this has to be in osm-fieldwork though as we need to know what the file format was for the pmtile or mbtile generation

**Comment by Sujanadh** [comment]
In `osm-fieldwork` , only two extensions (.jpg' , '.png') are checked and removed. Should I add more or leave it as it is?

**Comment by spwoodcock** [comment]
Should be fine - I have yet to see a `.webp` TMS server or anything else - if this changes in future we can address it 😄

**Comment by spwoodcock** [comment]
Rebased this to test an update to the PR Labeler workflow 👍 

Should we change this PR to be frontend based validation?
If the URL checks are good enough in osm-fieldwork we can just use those.
If not, the checks here may be useful: if extension exists, validate it is in list of options

**Comment by Sujanadh** [comment]
Yes, we can change this to frontend based validation.
URL checks in `osm-fieldwork` do work; it checks for any invalid placeholders in the URL. We can use that.

**Pull request closed without merging**
