### PR TITLE
Replace synchronous database driver with async (sqalchemy)

### PR DESCRIPTION
**Pull request by spwoodcock**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Issue

Related to #254

## Describe this PR

WORK IN PROGRESS

**We should probably do this alongside #254 to avoid having to implement in SQLAlchemy**
(the structure remains mostly the same when using the underlying driver)

Either (if using SQLAlchemy):

- [ ] Replace all `db.query` code with `db.select` or similar.

OR (if using psycopg/asyncpg):

- [ ] Replace all `db.query` code with direct driver usage via SQL.

Also:
- [ ] Add `await` to every instance of db usage...
- [ ] Fix running of test cases (untested).

Useful reference: https://praciano.com.br/fastapi-and-async-sqlalchemy-20-with-pytest-done-right.html

## Checklist before requesting a review

- 📖 Read the FMTM Contributing Guide: <https://github.com/hotosm/fmtm/blob/main/CONTRIBUTING.md>
- 📖 Read the FMTM Code of Conduct: <https://github.com/hotosm/fmtm/blob/main/CODE_OF_CONDUCT.md>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

### CODE REVIEW

**Comment by robsavoye** [comment]
https://github.com/hotosm/tm-admin/blob/main/docs/pgasync.md

**Comment by robsavoye** [comment]
https://github.com/hotosm/tm-admin/blob/main/docs/pgasync.md

**Comment by robsavoye** [comment]
https://github.com/hotosm/tm-admin/blob/main/docs/pgasync.md

**Comment by robsavoye** [comment]
There is a new database driver in osm-rawdata that is fuylly async. Just replace tm_admin.postgres with tm_admin.pgsync. I wrote a brief doc on how to use this module. https://github.com/hotosm/tm-admin/blob/main/docs/pgasync.md.

**Comment by spwoodcock** [comment]
From my understanding tm-admin won't replace the entire backend, but mostly the logic around administration of projects, users, orgs etc.

This PR is using `psycopg3`, but tm-admin uses `asyncpg`. To avoid additional dependencies, once tm-admin is integrated this PR should probably be updated to use `asyncpg`.

**Comment by spwoodcock** [comment]
We will likely replace this PR with a refactor of SQLAlchemy --> psycopg driver usage at the same time.

**Pull request closed without merging**
