### PR TITLE
fix: compose file name for backend test stage

### PR DESCRIPTION
**Pull request by nischalstha9**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 🧑‍💻 Refactor
- [ ] ✅ Test
- [X] 🤖 Build or CI
- [ ] ❓ Other (please specify)

### CODE REVIEW

**Review by Sujanadh — APPROVED** [review]

**Comment by Sujanadh** [comment]
```
stat /home/runner/work/fmtm/fmtm/docker-compose.yml: no such file or directory
Error: Process completed with exit code 14.
```

**Comment by spwoodcock** [comment]
Related to #1998. I did wonder if it might cause unintended issues somewhere, my apologies.

You need to include the `compose_file` var in the workflow I think

**Comment by spwoodcock** [comment]
Or is the issue perhaps within another workflow that has the image build workflow nested within? 😅 That would be a hassle.

If so, it might require updating the gh-workflows repo default compose file name, incrementing as a breaking MAJOR version, and creating a release. Then updating workflows in FMTM.

Alternatively, just revert the PR I linked above and we can address this later 😃

**Comment by nischalstha9** [comment]
I added the `compose_file` parameter but there was some error related to coverage. Not sure why it was not found in the test.
image
Meanwhile I have also created a PR reverting the commit #2021.
Will you review it.

**Comment by spwoodcock** [comment]
Mystery to me!

If it was going to be missing, I would think it would happen after the upgrade to use `uv`.

As far as I remember nothing related to the build has been done recently 🤔

**Pull request merged**
