### PR TITLE
Feat verification tag add

### LINKED ISSUE #1216: handling of info messages on frontend
**Describe the bug**
The message during task updates are said as "task has been updated to 1". This doesn't convey proper information to users.
also when user try to click update button without updating form. It also should show the message like "No change to update"

**To Reproduce**

1. Go to 'project page'
2. Click on 'any task to map '
3. See error

**Expected behavior**
The message like "Task id updated to locked for mapping". 

**Screenshots**
image

### PR DESCRIPTION
**Pull request by NSUWAL123**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Issue
- Fix #1216

## Describe this PR
This PR contains the following works: 
1. Verified or Not Verified tag add on organization card list
2. Task update info message fix

## Screenshots
1. 
image

2. 
image

### CODE REVIEW

**Comment by spwoodcock** [comment]
This will only be visible to the admin user right?

Please fix the conflict & I will merge 👍

**Comment by manjitapandey** [comment]
@spwoodcock I think it should be visible to all the users who change the state of any task

**Comment by spwoodcock** [comment]
But viewing the unapproved orgs is an admin only endpoint, so this isn't possible. 

I don't think we should let everyone view the org until it is approved. So in reality the only person which will see these tags is the admin

**Comment by manjitapandey** [comment]
Sorry, looks like a kind of misunderstanding here. I completely agree it with the first pic. I kinda misunderstood with second one, which will be seen by all the users who changes the state of task. 
Apologies for the confusions

**Comment by NSUWAL123** [comment]
@spwoodcock, I have resolved the merge conflict. You can merge it now

**Pull request merged**
