### PR TITLE
Inform user if GeoJSON CRS is not EPSG:4326

### PR DESCRIPTION
**Pull request by Sujanadh**
fixes: #911 
This pull request aims to standardize the Coordinate Reference Systems (CRS) in our GeoJSON data by converting them to the  EPSG:4326 standard.
pyproj is used to change the coordinate reference system.

### CODE REVIEW

**Comment by spwoodcock** [comment]
GeoJSON can have a `crs` property, but rarely is it ever set.

What happens if we pass a GeoJSON without this property?
We should fallback to parsing as EPSG 4326.

**Comment by robsavoye** [comment]
I have had no problems using GeoJson files with no crs as AOIs, and it appears 4326 is the default.

**Review by nrjadkry — COMMENTED** [review]
@spwoodcock  it looks like @Sujanadh  have used pyproj.
It it okay if we used this package?

**Comment by spwoodcock** [comment]
@robsavoye `crs` isn't a mandatory key for GeoJSON, and it's rarely used. There is no default per se, just software that parse geojson will generally assume it's in EPSG4326.

See https://github.com/hotosm/fmtm/issues/911#issuecomment-1767551816 too.

**Comment by robsavoye** [comment]
I'm curious what program generated a GeoJson files with a non 4326 crs ?

**Comment by spwoodcock** [comment]
@nrjadkry good point - we will need to install system package `libproj`, which isn't ideal.

IMO we should shelve this PR for now, until we support formats other than GeoJSON.
Determining the CRS of a GeoJSON, if the user doesn't provide a `crs` key is difficult.
If the user uploads e.g. a geopackage, then it's much easier to handle crs.

**Comment by robsavoye** [comment]
I think for a project AOI, we should stick to GeoJson. A shapefile is usually not just a polygon, it's more like a FeatureCollection. It's possible to transform not using libproj, but I think for now we can default to GeoJson, and if it's another format, they can use ogr2ogr to transform the projection.

**Comment by spwoodcock** [comment]
Actually, ignore my previous comment. We currently install `libproj` anyway, probably for shapely.
Adding pyproj is fine.

To make this workable for now, @Sujanadh could we please:
- Update the code to skip the CRS check if the `crs` key is not present in the GeoJSON.
- If the `crs` key is present. then transform to EPSG 4326.
- If the GeoJSON can't be transformed, return an error message to inform the user.

**Comment by nrjadkry** [comment]
Is it okay, if we throw an exception if it is in other format than 4326, and asks users to have tht geojson in 4326?

**Comment by spwoodcock** [comment]
Yes, that also works.
If the `crs` key is present, and anything other than 4326, then throw an error and inform the user.

**Comment by spwoodcock** [comment]
@robsavoye this isn't a priority, but GeoJSON isn't necessarily the most common format for GIS users. Others, even KML, would be useful. We can wait to see if any user feedback suggests this though & forget about it for now.

The nice thing is we can probably just tell users to go to geojson.io to generate one easily.

Saying 'just use ogr2ogr2' isn't an option for many users.

**Comment by robsavoye** [comment]
What does TM use for an AOI ? I think just GeoJson or drawing the polygon by hand.

**Comment by spwoodcock** [comment]
@nrjadkry

I was going to suggest that we update the error handling for the `preview_tasks` endpoint to account for the scenario in #911.

But I think a better solution is to fix the crs parsing, so this shouldn't happen hopefully.

In addition to checking for invalid values for the `crs` key, we should also parse the coordinates and check they are inside bounds: -180.0 -90.0 180.0 90.0 (EPSG 4326).
If they are not, then also throw an error.

**Comment by spwoodcock** [comment]
@robsavoye good point, having the 'draw by hand' feature working solves this issue.

**Comment by nrjadkry** [comment]
> @nrjadkry
> 
> I was going to suggest that we update the error handling for the `preview_tasks` endpoint to account for the scenario in #911.
> 
> But I think a better solution is to fix the crs parsing, so this shouldn't happen hopefully.
> 
> In addition to checking for invalid values for the `crs` key, we should also parse the coordinates and check they are inside bounds: -180.0 -90.0 180.0 90.0 (EPSG 4326). If they are not, then also throw an error.

Okay @spwoodcock , we will make these changes.
1. We will check if the crs key is present. if crs is other than 4326, throw an error.
2. Check the bounds for the coordinates,  if they are not in -180.0 -90.0 180.0 90.0 (EPSG 4326), we throw an error.

**Comment by Sujanadh** [comment]
This new changes removes the conversion function and simply handles the geojson and return error message if other than WGS 84/EPSG:4326.

**Review by spwoodcock — APPROVED** [review]

**Pull request merged**
