### PR TITLE
Fix Edit Project Name

### PR DESCRIPTION
**Pull request by Sujanadh**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue

- issue #1412

## Describe this PR

This PR addresses this issue by correcting `project_prefix_name` to `name` which is obtained from the payload as project metadata.

## Screenshots

N/A

## Alternative Approaches Considered

Did you attempt any other approaches that are not documented in code?

## Review Guide

Notes for the reviewer. How to test this change?

## Checklist before requesting a review

- 📖 Read the FMTM Contributing Guide: <https://github.com/hotosm/fmtm/blob/main/CONTRIBUTING.md>
- 📖 Read the HOT Code of Conduct: <https://docs.hotosm.org/code-of-conduct>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

### CODE REVIEW

**Review by spwoodcock — COMMENTED** [review]
Is project_name_prefix the correct place to store this value?

I thought that field was automatically computed as a lowercase and underscore joined version of the project name

**Comment by spwoodcock** [comment]
Like this one:

https://github.com/hotosm/fmtm/blob/development/src%2Fbackend%2Fapp%2Fprojects%2Fproject_schemas.py#L179

We should save to the name field, then compute the name prefix in the pydantic model used in the endpoint.

**Comment by Sujanadh** [comment]
oh yeah, you are right. But the pydantic model in our case is mostly used for returning the desired response after validation but not for saving data to the database.

**Comment by Sujanadh** [comment]
added a calculate method to edit the project prefix name in the schema of the partial update too. we can refactor some repeated code later.

**Review by spwoodcock — APPROVED** [review]

**Pull request merged**
