### PR TITLE
Selection of basemap output formats, TMS input, mobile UI

### LINKED ISSUE #586: Support mbtile, sqlite, pmtile basemap generation
Imagery basemaps are very useful in the field when the map data isn't very complete. Osm-fieldwork has a **basemapper.py** program which downloads map tiles from several different sources. It creates an XYZ map tile store on disk, and using a boundary polygon, extracts the tiles that fit in that boundary. It can write both .mbtiles for ODK Collect, and sqlitedb files for Osmand. Both output formats should be supported.

**EDIT** mbtiles have been implemented. We still need mbtile and pmtile at some point.

### LINKED ISSUE #839: MBTile generation, allow custom url input
- We can currently use 4 different providers for mbtile generation (the mbtiles feature is awesome btw!)
- The module in osm-fieldwork currently support custom URLs for the imagery.
- The frontend should support this.

This feature is needed for the demo next week.

### PR DESCRIPTION
**Pull request by spwoodcock**
**Note: this requires osm-fieldwork v0.3.7 or v0.4.0**

I quickly made the PR as I had been working on osm-fieldwork basemapper.py and had it fresh in my head (avoid context switching).

Fixes #839 and fixes #586 

- Selection of mbtiles, osmand (sqlite) and pmtiles formats for basemap generation.
- Use custom TMS URL for input.
- Fixed mobile UI for tile generation modal.

@varun2948 I didn't spend too long on the UI part. I didn't want to duplicate work you may be doing already. But I just made it work on mobile as well as desktop 👍

### CODE REVIEW

**Comment by varun2948** [comment]
@spwoodcock sounds good to me will have a look onto this branch aswell thanks for the feature on both side frontend backend .

**Comment by varun2948** [comment]
@spwoodcock i am having this issue on this branch on my local server any idea ? 

`from osm_fieldwork.basemapper import create_basemap_file
fmtm_api         | ImportError: cannot import name 'create_basemap_file' from 'osm_fieldwork.basemapper' (/home/appuser/.local/lib/python3.10/site-packages/osm_fieldwork/basemapper.py)
`

**Comment by spwoodcock** [comment]
This needs a new release of osm-fieldwork.

You can bind mount a local version - see the dev backend docs 👍

**Comment by varun2948** [comment]
@spwoodcock now using development version of osm-fieldwork, I am getting error like this 
`  File "/opt/app/central/central_routes.py", line 33, in <module>
    from ..projects import project_crud, project_schemas
  File "/opt/app/projects/project_crud.py", line 41, in <module>
    from osm_fieldwork.basemapper import create_basemap_file
  File "/home/appuser/.local/lib/python3.10/site-packages/osm_fieldwork/basemapper.py", line 34, in <module>
    from pmtiles.tile import (
ModuleNotFoundError: No module named 'pmtiles'
`

**Comment by spwoodcock** [comment]
You need to rebuild the backend image using this branch.

It has the `pmtiles` dependency added.

**Comment by spwoodcock** [comment]
Nice 🤩

The migration looks good 👍

I was determining the format using the file extension - I'll have to check the download endpoint - we can probably use this new field instead. (I understand the new field is required to display the format without downloading the file).

Just fyi, I don't really envision the pmtiles format will be requested by a user, as it's an online only format (although they could, so we can give the option. 

The idea of pmtiles was to:
- Generate the entire project area in pmtiles when the project is created.
- A user requests an area to download in mbtiles or sqlite format.
- The backend grabs the tiles from S3 based pmtiles via RANGE request, and packages the tiles in the requested format (so they can view their area offline).

**Comment by varun2948** [comment]
Yeah 
My initial thought about the output_format was to extract it from the path and use that but then just did it with another field as it seemed reasonable as it already had a column for source. 

Hmm about the PMtiles it was just requested by Rob so i guess we went ahead and did it for PMTiles too but i understand what you're trying to say.

**Pull request merged**
